/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, once) {

  function myFunction() {
    console.log('Faith Subscriptions theme scripts is alive and well.');
  };

  myFunction();
})(jQuery, Drupal, once);